"""baseline — full schema of 11-data-model.md v2

Creates every table, index, CHECK/FK/UNIQUE constraint, the two SQL views
(``current_band_estimates``, ``scored_attempts``) and the ``vocab_fts`` FTS5 index with its
sync triggers. Runs clean on an empty database.

The table DDL below is autogenerated from ``bandready.db.models``. The DESC-ordered indexes and
everything Alembic cannot autogenerate (views, virtual tables, triggers) are appended by hand —
their DDL lives in ``bandready.db.views``.

Revision ID: 0001
Revises:
Create Date: 2026-07-25

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from bandready.db.views import create_views, create_vocab_fts, drop_views, drop_vocab_fts

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Indexes with a DESC term. SQLAlchemy/Alembic cannot reflect expression-based indexes on
#: SQLite, so autogenerate skips them and they are managed explicitly here.
DESC_INDEXES: tuple[tuple[str, str], ...] = (
    ("ix_practice_sessions_feed", "practice_sessions(profile_id, started_at DESC)"),
    ("ix_practice_sessions_mod", "practice_sessions(profile_id, module, started_at DESC)"),
    ("ix_writing_evals_sub", "writing_evaluations(submission_id, created_at DESC)"),
    ("ix_llm_evals_subject", "llm_evaluations(subject_kind, subject_id, created_at DESC)"),
    ("ix_placement_results_profile", "placement_results(profile_id, taken_at DESC)"),
    ("ix_study_plans_profile", "study_plans(profile_id, generated_at DESC)"),
    ("ix_adaptive_events_feed", "adaptive_events(profile_id, fired_at DESC)"),
    ("ix_activity_log_feed", "activity_log(profile_id, at DESC)"),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_packs',
    sa.Column('pack_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('publisher', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('ai_disclosure', sa.Text(), server_default=sa.text("'human'"), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('installed_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("ai_disclosure IN ('human','ai_assisted','ai_generated')", name=op.f('ck_content_packs_ai_disclosure')),
    sa.CheckConstraint('enabled IN (0,1)', name=op.f('ck_content_packs_enabled')),
    sa.PrimaryKeyConstraint('pack_id', 'version', name=op.f('pk_content_packs'))
    )
    op.create_table('llm_evaluations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_kind', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('temperature', sa.REAL(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=True),
    sa.Column('overall_band', sa.REAL(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("purpose IN ('score','rescore','trap_analysis','coach','generation_validation')", name=op.f('ck_llm_evaluations_purpose')),
    sa.CheckConstraint("status IN ('ok','parse_failed','api_failed')", name=op.f('ck_llm_evaluations_status')),
    sa.CheckConstraint("subject_kind IN ('speaking_session','writing_submission','reading_attempt','listening_attempt','vocab_entry','placement')", name=op.f('ck_llm_evaluations_subject_kind')),
    sa.CheckConstraint('overall_band BETWEEN 0 AND 9', name=op.f('ck_llm_evaluations_overall_band')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_evaluations'))
    )
    with op.batch_alter_table('llm_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_llm_evals_calib', ['prompt_version', 'model_id', 'status'], unique=False)

    op.create_table('media_files',
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('last_access_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("kind IN ('listening_render','tts_line','vocab_audio','pron_ref','pack_media')", name=op.f('ck_media_files_kind')),
    sa.CheckConstraint('pinned IN (0,1)', name=op.f('ck_media_files_pinned')),
    sa.PrimaryKeyConstraint('hash', name=op.f('pk_media_files'))
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index('ix_media_evict', ['pinned', 'kind', 'last_access_at'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('exam_format', sa.Text(), server_default=sa.text("'academic'"), nullable=False),
    sa.Column('target_band', sa.REAL(), nullable=True),
    sa.Column('exam_date', sa.Text(), nullable=True),
    sa.Column('self_level', sa.Text(), nullable=True),
    sa.Column('daily_minutes', sa.Integer(), server_default=sa.text('(60)'), nullable=False),
    sa.Column('study_days_json', sa.Text(), server_default=sa.text('\'["mon","tue","wed","thu","fri","sat"]\''), nullable=False),
    sa.Column('onboarded_at', sa.Text(), nullable=True),
    sa.Column('placement_completed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("exam_format IN ('academic','general_training')", name=op.f('ck_profiles_exam_format')),
    sa.CheckConstraint("self_level IN ('beginner','intermediate','upper','advanced')", name=op.f('ck_profiles_self_level')),
    sa.CheckConstraint('daily_minutes IN (30,60,90)', name=op.f('ck_profiles_daily_minutes')),
    sa.CheckConstraint('target_band BETWEEN 4 AND 9', name=op.f('ck_profiles_target_band')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('topics',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), server_default=sa.text("'general'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_table('vocab_pack_entries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lemma', sa.Text(), nullable=False),
    sa.Column('pos', sa.Text(), server_default=sa.text("'other'"), nullable=False),
    sa.Column('deck', sa.Text(), nullable=False),
    sa.Column('entry_json', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_vocab_pack_entries_source')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_vocab_pack_entries_retired')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_pack_entries'))
    )
    with op.batch_alter_table('vocab_pack_entries', schema=None) as batch_op:
        batch_op.create_index('ix_vocab_pack_entries_deck', ['deck', 'retired'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('ref_kind', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_activity_log_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_table('adaptive_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('fired_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=False),
    sa.Column('dismissed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_adaptive_events_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adaptive_events'))
    )
    op.create_table('band_estimates',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('skill', sa.Text(), nullable=False),
    sa.Column('estimate_raw', sa.REAL(), nullable=True),
    sa.Column('band', sa.REAL(), nullable=False),
    sa.Column('range_low', sa.REAL(), nullable=True),
    sa.Column('range_high', sa.REAL(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('n_eff', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempts_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('newest_attempt_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("confidence IN ('insufficient','low','medium','high')", name=op.f('ck_band_estimates_confidence')),
    sa.CheckConstraint("method IN ('estimator','placement','self_assessed','manual')", name=op.f('ck_band_estimates_method')),
    sa.CheckConstraint("skill IN ('speaking','writing','reading','listening','overall')", name=op.f('ck_band_estimates_skill')),
    sa.CheckConstraint('band BETWEEN 0 AND 9', name=op.f('ck_band_estimates_band')),
    sa.CheckConstraint('range_high BETWEEN 0 AND 9', name=op.f('ck_band_estimates_range_high')),
    sa.CheckConstraint('range_low BETWEEN 0 AND 9', name=op.f('ck_band_estimates_range_low')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_band_estimates_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_band_estimates'))
    )
    with op.batch_alter_table('band_estimates', schema=None) as batch_op:
        batch_op.create_index('ix_band_estimates_trend', ['profile_id', 'skill', 'created_at'], unique=False)

    op.create_table('card_sets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('parts_json', sa.Text(), server_default=sa.text("'[1,2,3]'"), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('last_served_at', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_card_sets_source')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_card_sets_retired')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_card_sets_topics_topic_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_sets'))
    )
    with op.batch_alter_table('card_sets', schema=None) as batch_op:
        batch_op.create_index('ix_card_sets_pick', ['retired', 'last_served_at'], unique=False)

    op.create_table('daily_activity',
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('goal_met', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_rest_day', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('streak_repaired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('goal_met IN (0,1)', name=op.f('ck_daily_activity_goal_met')),
    sa.CheckConstraint('is_rest_day IN (0,1)', name=op.f('ck_daily_activity_is_rest_day')),
    sa.CheckConstraint('streak_repaired IN (0,1)', name=op.f('ck_daily_activity_streak_repaired')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_daily_activity_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'date', name=op.f('pk_daily_activity'))
    )
    op.create_table('listening_scripts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('accent_set', sa.Text(), server_default=sa.text("'uk'"), nullable=False),
    sa.Column('target_band', sa.REAL(), nullable=False),
    sa.Column('script_json', sa.Text(), nullable=False),
    sa.Column('audio_hash', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("accent_set IN ('uk','us','au')", name=op.f('ck_listening_scripts_accent_set')),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_listening_scripts_source')),
    sa.CheckConstraint('part BETWEEN 1 AND 4', name=op.f('ck_listening_scripts_part')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_listening_scripts_retired')),
    sa.CheckConstraint('target_band BETWEEN 0 AND 9', name=op.f('ck_listening_scripts_target_band')),
    sa.ForeignKeyConstraint(['audio_hash'], ['media_files.hash'], name=op.f('fk_listening_scripts_media_files_audio_hash')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_listening_scripts_topics_topic_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_scripts'))
    )
    with op.batch_alter_table('listening_scripts', schema=None) as batch_op:
        batch_op.create_index('ix_listening_scripts_pick', ['part', 'target_band', 'retired'], unique=False)

    op.create_table('milestones',
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('milestone_id', sa.Text(), nullable=False),
    sa.Column('achieved_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_milestones_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'milestone_id', name=op.f('pk_milestones'))
    )
    op.create_table('placement_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('taken_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('estimates_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_placement_results_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_results'))
    )
    op.create_table('practice_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.CheckConstraint("module IN ('speaking','writing','reading','listening','vocab','drill','placement')", name=op.f('ck_practice_sessions_module')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_practice_sessions_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sessions'))
    )
    op.create_table('pron_drill_attempts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('drill_type', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('contrast', sa.Text(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("drill_type IN ('minimal_pair_ab','word_stress_tap')", name=op.f('ck_pron_drill_attempts_drill_type')),
    sa.CheckConstraint('correct IN (0,1)', name=op.f('ck_pron_drill_attempts_correct')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_pron_drill_attempts_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pron_drill_attempts'))
    )
    with op.batch_alter_table('pron_drill_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_pron_drills_contrast', ['profile_id', 'contrast', 'created_at'], unique=False)

    op.create_table('readiness_items',
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('checked', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('checked_at', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('auto','manual')", name=op.f('ck_readiness_items_kind')),
    sa.CheckConstraint('checked IN (0,1)', name=op.f('ck_readiness_items_checked')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_readiness_items_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'item_id', name=op.f('pk_readiness_items'))
    )
    op.create_table('reading_passages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('band_target', sa.REAL(), nullable=True),
    sa.Column('passage_json', sa.Text(), nullable=False),
    sa.Column('validation_report_json', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("format IN ('academic','general_training')", name=op.f('ck_reading_passages_format')),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_reading_passages_source')),
    sa.CheckConstraint('band_target BETWEEN 0 AND 9', name=op.f('ck_reading_passages_band_target')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_reading_passages_retired')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_reading_passages_topics_topic_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_passages'))
    )
    with op.batch_alter_table('reading_passages', schema=None) as batch_op:
        batch_op.create_index('ix_reading_passages_pick', ['format', 'band_target', 'retired'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('goal_band', sa.REAL(), nullable=False),
    sa.Column('exam_date', sa.Text(), nullable=True),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('rationale_json', sa.Text(), nullable=True),
    sa.Column('superseded_by', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('goal_band BETWEEN 4 AND 9', name=op.f('ck_study_plans_goal_band')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_study_plans_profiles_profile_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['study_plans.id'], name=op.f('fk_study_plans_study_plans_superseded_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans'))
    )
    op.create_table('vocab_entries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('headword', sa.Text(), nullable=False),
    sa.Column('lemma', sa.Text(), nullable=False),
    sa.Column('pos', sa.Text(), server_default=sa.text("'other'"), nullable=False),
    sa.Column('is_phrase', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ipa', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('own_context_sentence', sa.Text(), nullable=True),
    sa.Column('own_context_origin', sa.Text(), server_default=sa.text("'seed'"), nullable=False),
    sa.Column('example_sentences_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('collocations_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('topic_tags_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('cefr_level', sa.Text(), nullable=True),
    sa.Column('audio_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'suggested'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("cefr_level IN ('A1','A2','B1','B2','C1','C2')", name=op.f('ck_vocab_entries_cefr_level')),
    sa.CheckConstraint("own_context_origin IN ('seed','learner')", name=op.f('ck_vocab_entries_own_context_origin')),
    sa.CheckConstraint("pos IN ('noun','verb','adj','adv','prep','phrase','collocation','other')", name=op.f('ck_vocab_entries_pos')),
    sa.CheckConstraint("status IN ('suggested','active','suspended','known')", name=op.f('ck_vocab_entries_status')),
    sa.CheckConstraint('is_phrase IN (0,1)', name=op.f('ck_vocab_entries_is_phrase')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_vocab_entries_profiles_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_entries')),
    sa.UniqueConstraint('profile_id', 'lemma', 'pos', name='uq_vocab_entries_profile_lemma_pos')
    )
    with op.batch_alter_table('vocab_entries', schema=None) as batch_op:
        batch_op.create_index('ix_vocab_entries_browse', ['profile_id', 'status'], unique=False)
        batch_op.create_index('ix_vocab_entries_lemma', ['profile_id', 'lemma'], unique=False)

    op.create_table('writing_prompts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('topic_tags', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('difficulty', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('chart_spec', sa.Text(), nullable=True),
    sa.Column('letter_bullets', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_writing_prompts_source')),
    sa.CheckConstraint("task_type IN ('ac_task1','gt_task1','task2')", name=op.f('ck_writing_prompts_task_type')),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name=op.f('ck_writing_prompts_difficulty')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_writing_prompts_retired')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_writing_prompts_topics_topic_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_prompts'))
    )
    with op.batch_alter_table('writing_prompts', schema=None) as batch_op:
        batch_op.create_index('ix_writing_prompts_pick', ['task_type', 'genre', 'difficulty', 'retired'], unique=False)

    op.create_table('drill_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('drill_kind', sa.Text(), nullable=False),
    sa.Column('qtype', sa.Text(), nullable=True),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('n_correct', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.CheckConstraint("module IN ('reading','listening','vocab')", name=op.f('ck_drill_results_module')),
    sa.ForeignKeyConstraint(['id'], ['practice_sessions.id'], name=op.f('fk_drill_results_practice_sessions_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill_results'))
    )
    with op.batch_alter_table('drill_results', schema=None) as batch_op:
        batch_op.create_index('ix_drill_results_kind', ['module', 'drill_kind', 'qtype'], unique=False)

    op.create_table('listening_questions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('script_id', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.Text(), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('cue_line_index', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['listening_scripts.id'], name=op.f('fk_listening_questions_listening_scripts_script_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_questions')),
    sa.UniqueConstraint('script_id', 'number', name='uq_listening_questions_script_number')
    )
    with op.batch_alter_table('listening_questions', schema=None) as batch_op:
        batch_op.create_index('ix_listening_questions_type', ['qtype'], unique=False)

    op.create_table('listening_tests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('p1_id', sa.Text(), nullable=False),
    sa.Column('p2_id', sa.Text(), nullable=False),
    sa.Column('p3_id', sa.Text(), nullable=False),
    sa.Column('p4_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_listening_tests_source')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_listening_tests_retired')),
    sa.ForeignKeyConstraint(['p1_id'], ['listening_scripts.id'], name=op.f('fk_listening_tests_listening_scripts_p1_id')),
    sa.ForeignKeyConstraint(['p2_id'], ['listening_scripts.id'], name=op.f('fk_listening_tests_listening_scripts_p2_id')),
    sa.ForeignKeyConstraint(['p3_id'], ['listening_scripts.id'], name=op.f('fk_listening_tests_listening_scripts_p3_id')),
    sa.ForeignKeyConstraint(['p4_id'], ['listening_scripts.id'], name=op.f('fk_listening_tests_listening_scripts_p4_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_tests'))
    )
    op.create_table('plan_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('blocks_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('minutes_logged', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_block', sa.Integer(), nullable=True),
    sa.CheckConstraint("phase IN ('build','taper')", name=op.f('ck_plan_sessions_phase')),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed','partial','skipped')", name=op.f('ck_plan_sessions_status')),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], name=op.f('fk_plan_sessions_study_plans_plan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_sessions'))
    )
    with op.batch_alter_table('plan_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_plan_sessions_day', ['plan_id', 'date'], unique=False)

    op.create_table('reading_questions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('passage_id', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('group_index', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.Text(), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('anchor_paragraphs_json', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('trap_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], name=op.f('fk_reading_questions_reading_passages_passage_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_questions')),
    sa.UniqueConstraint('passage_id', 'number', name='uq_reading_questions_passage_number')
    )
    with op.batch_alter_table('reading_questions', schema=None) as batch_op:
        batch_op.create_index('ix_reading_questions_type', ['qtype'], unique=False)

    op.create_table('reading_tests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('p1_id', sa.Text(), nullable=False),
    sa.Column('p2_id', sa.Text(), nullable=False),
    sa.Column('p3_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("format IN ('academic','general_training')", name=op.f('ck_reading_tests_format')),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_reading_tests_source')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_reading_tests_retired')),
    sa.ForeignKeyConstraint(['p1_id'], ['reading_passages.id'], name=op.f('fk_reading_tests_reading_passages_p1_id')),
    sa.ForeignKeyConstraint(['p2_id'], ['reading_passages.id'], name=op.f('fk_reading_tests_reading_passages_p2_id')),
    sa.ForeignKeyConstraint(['p3_id'], ['reading_passages.id'], name=op.f('fk_reading_tests_reading_passages_p3_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_tests'))
    )
    op.create_table('speaking_cards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('card_set_id', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), server_default=sa.text("'core'"), nullable=False),
    sa.Column('tags_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('last_served_at', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'pack'"), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=True),
    sa.Column('pack_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('retired', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("difficulty IN ('core','stretch')", name=op.f('ck_speaking_cards_difficulty')),
    sa.CheckConstraint("source IN ('pack','generated','user')", name=op.f('ck_speaking_cards_source')),
    sa.CheckConstraint('part BETWEEN 1 AND 3', name=op.f('ck_speaking_cards_part')),
    sa.CheckConstraint('retired IN (0,1)', name=op.f('ck_speaking_cards_retired')),
    sa.ForeignKeyConstraint(['card_set_id'], ['card_sets.id'], name=op.f('fk_speaking_cards_card_sets_card_set_id')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_speaking_cards_topics_topic_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_cards'))
    )
    with op.batch_alter_table('speaking_cards', schema=None) as batch_op:
        batch_op.create_index('ix_speaking_cards_pick', ['part', 'difficulty', 'retired', 'last_served_at'], unique=False)
        batch_op.create_index('ix_speaking_cards_set', ['card_set_id'], unique=False)

    op.create_table('speaking_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.Column('card_set_id', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('transcript_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('overall_band', sa.REAL(), nullable=True),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('pron_summary_json', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('placement','mock','practice','micro')", name=op.f('ck_speaking_sessions_mode')),
    sa.CheckConstraint("status IN ('active','complete','aborted','failed')", name=op.f('ck_speaking_sessions_status')),
    sa.CheckConstraint('overall_band BETWEEN 0 AND 9', name=op.f('ck_speaking_sessions_overall_band')),
    sa.CheckConstraint('part BETWEEN 1 AND 3', name=op.f('ck_speaking_sessions_part')),
    sa.ForeignKeyConstraint(['card_set_id'], ['card_sets.id'], name=op.f('fk_speaking_sessions_card_sets_card_set_id')),
    sa.ForeignKeyConstraint(['id'], ['practice_sessions.id'], name=op.f('fk_speaking_sessions_practice_sessions_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_sessions'))
    )
    op.create_table('srs_cards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entry_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('stability', sa.REAL(), nullable=True),
    sa.Column('difficulty', sa.REAL(), nullable=True),
    sa.Column('due_at', sa.Text(), nullable=False),
    sa.Column('last_review_at', sa.Text(), nullable=True),
    sa.Column('reps', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lapses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fsrs_json', sa.Text(), nullable=False),
    sa.CheckConstraint('state IN (0,1,2,3)', name=op.f('ck_srs_cards_state')),
    sa.ForeignKeyConstraint(['entry_id'], ['vocab_entries.id'], name=op.f('fk_srs_cards_vocab_entries_entry_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_srs_cards')),
    sa.UniqueConstraint('entry_id', name=op.f('uq_srs_cards_entry_id'))
    )
    with op.batch_alter_table('srs_cards', schema=None) as batch_op:
        batch_op.create_index('ix_srs_cards_due', ['due_at'], unique=False)

    op.create_table('vocab_sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entry_id', sa.Text(), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("module IN ('speaking','writing','reading','listening','pronunciation','seed','manual')", name=op.f('ck_vocab_sources_module')),
    sa.ForeignKeyConstraint(['entry_id'], ['vocab_entries.id'], name=op.f('fk_vocab_sources_vocab_entries_entry_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_sources'))
    )
    with op.batch_alter_table('vocab_sources', schema=None) as batch_op:
        batch_op.create_index('ix_vocab_sources_entry', ['entry_id'], unique=False)

    op.create_table('writing_submissions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('prompt_id', sa.Text(), nullable=False),
    sa.Column('parent_submission_id', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('essay_text', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('outline_text', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('word_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('seconds_elapsed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('overtime_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('paste_events', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('integrity_flag', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.Text(), nullable=True),
    sa.Column('overall_band', sa.REAL(), nullable=True),
    sa.CheckConstraint("mode IN ('exam','practice')", name=op.f('ck_writing_submissions_mode')),
    sa.CheckConstraint("status IN ('draft','submitted','scored','failed')", name=op.f('ck_writing_submissions_status')),
    sa.CheckConstraint('overall_band BETWEEN 0 AND 9', name=op.f('ck_writing_submissions_overall_band')),
    sa.ForeignKeyConstraint(['id'], ['practice_sessions.id'], name=op.f('fk_writing_submissions_practice_sessions_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_submission_id'], ['writing_submissions.id'], name=op.f('fk_writing_submissions_writing_submissions_parent_submission_id')),
    sa.ForeignKeyConstraint(['prompt_id'], ['writing_prompts.id'], name=op.f('fk_writing_submissions_writing_prompts_prompt_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_submissions'))
    )
    with op.batch_alter_table('writing_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_writing_submissions_parent', ['parent_submission_id'], unique=False)
        batch_op.create_index('ix_writing_submissions_prompt', ['prompt_id'], unique=False)

    op.create_table('listening_attempts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('test_id', sa.Text(), nullable=True),
    sa.Column('script_id', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('band', sa.REAL(), nullable=True),
    sa.Column('duration_s', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('submitted_at', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('exam','practice','dictation','accent_drill')", name=op.f('ck_listening_attempts_mode')),
    sa.CheckConstraint("status IN ('in_progress','submitted','abandoned')", name=op.f('ck_listening_attempts_status')),
    sa.CheckConstraint('(test_id IS NULL) <> (script_id IS NULL)', name=op.f('ck_listening_attempts_target')),
    sa.CheckConstraint('band BETWEEN 0 AND 9', name=op.f('ck_listening_attempts_band')),
    sa.ForeignKeyConstraint(['id'], ['practice_sessions.id'], name=op.f('fk_listening_attempts_practice_sessions_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['listening_scripts.id'], name=op.f('fk_listening_attempts_listening_scripts_script_id')),
    sa.ForeignKeyConstraint(['test_id'], ['listening_tests.id'], name=op.f('fk_listening_attempts_listening_tests_test_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_attempts'))
    )
    op.create_table('reading_attempts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('test_id', sa.Text(), nullable=True),
    sa.Column('passage_id', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('band', sa.REAL(), nullable=True),
    sa.Column('duration_s', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('exam','practice')", name=op.f('ck_reading_attempts_mode')),
    sa.CheckConstraint("status IN ('in_progress','submitted','abandoned')", name=op.f('ck_reading_attempts_status')),
    sa.CheckConstraint('(test_id IS NULL) <> (passage_id IS NULL)', name=op.f('ck_reading_attempts_target')),
    sa.CheckConstraint('band BETWEEN 0 AND 9', name=op.f('ck_reading_attempts_band')),
    sa.ForeignKeyConstraint(['id'], ['practice_sessions.id'], name=op.f('fk_reading_attempts_practice_sessions_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], name=op.f('fk_reading_attempts_reading_passages_passage_id')),
    sa.ForeignKeyConstraint(['test_id'], ['reading_tests.id'], name=op.f('fk_reading_attempts_reading_tests_test_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_attempts'))
    )
    op.create_table('speaking_turns',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('t_ms', sa.Integer(), nullable=False),
    sa.Column('dur_ms', sa.Integer(), nullable=True),
    sa.Column('segments_json', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name=op.f('ck_speaking_turns_role')),
    sa.ForeignKeyConstraint(['session_id'], ['speaking_sessions.id'], name=op.f('fk_speaking_turns_speaking_sessions_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_turns')),
    sa.UniqueConstraint('session_id', 'turn_index', name='uq_speaking_turns_session_turn')
    )
    op.create_table('srs_review_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('state_before', sa.Integer(), nullable=False),
    sa.Column('stability_before', sa.REAL(), nullable=True),
    sa.Column('difficulty_before', sa.REAL(), nullable=True),
    sa.CheckConstraint("review_type IN ('flip','cloze','use_in_sentence','collocation','audio_recall','speaking_drill')", name=op.f('ck_srs_review_logs_review_type')),
    sa.CheckConstraint('rating BETWEEN 1 AND 4', name=op.f('ck_srs_review_logs_rating')),
    sa.ForeignKeyConstraint(['card_id'], ['srs_cards.id'], name=op.f('fk_srs_review_logs_srs_cards_card_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_srs_review_logs'))
    )
    with op.batch_alter_table('srs_review_logs', schema=None) as batch_op:
        batch_op.create_index('ix_srs_review_logs_card', ['card_id', 'reviewed_at'], unique=False)
        batch_op.create_index('ix_srs_review_logs_time', ['reviewed_at'], unique=False)

    op.create_table('writing_evaluations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('llm_evaluation_id', sa.Text(), nullable=False),
    sa.Column('band_ta', sa.REAL(), nullable=False),
    sa.Column('band_cc', sa.REAL(), nullable=False),
    sa.Column('band_lr', sa.REAL(), nullable=False),
    sa.Column('band_gra', sa.REAL(), nullable=False),
    sa.Column('overall_band', sa.REAL(), nullable=False),
    sa.Column('annotations_json', sa.Text(), nullable=False),
    sa.Column('vocab_suggestions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('band_cc BETWEEN 0 AND 9', name=op.f('ck_writing_evaluations_band_cc')),
    sa.CheckConstraint('band_gra BETWEEN 0 AND 9', name=op.f('ck_writing_evaluations_band_gra')),
    sa.CheckConstraint('band_lr BETWEEN 0 AND 9', name=op.f('ck_writing_evaluations_band_lr')),
    sa.CheckConstraint('band_ta BETWEEN 0 AND 9', name=op.f('ck_writing_evaluations_band_ta')),
    sa.CheckConstraint('overall_band BETWEEN 0 AND 9', name=op.f('ck_writing_evaluations_overall_band')),
    sa.ForeignKeyConstraint(['submission_id'], ['writing_submissions.id'], name=op.f('fk_writing_evaluations_writing_submissions_submission_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_evaluations'))
    )
    op.create_table('listening_answers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('qtype', sa.Text(), nullable=False),
    sa.Column('given', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('normalized', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.CheckConstraint('correct IN (0,1)', name=op.f('ck_listening_answers_correct')),
    sa.ForeignKeyConstraint(['attempt_id'], ['listening_attempts.id'], name=op.f('fk_listening_answers_listening_attempts_attempt_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['listening_questions.id'], name=op.f('fk_listening_answers_listening_questions_question_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_listening_answers_attempt_question')
    )
    with op.batch_alter_table('listening_answers', schema=None) as batch_op:
        batch_op.create_index('ix_listening_answers_q', ['question_id'], unique=False)
        batch_op.create_index('ix_listening_answers_type', ['qtype', 'correct'], unique=False)

    op.create_table('pron_scores',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('turn_id', sa.Text(), nullable=True),
    sa.Column('passage_id', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('expected_ipa', sa.Text(), nullable=True),
    sa.Column('heard_approx', sa.Text(), nullable=True),
    sa.Column('t_start_ms', sa.Integer(), nullable=True),
    sa.Column('t_end_ms', sa.Integer(), nullable=True),
    sa.Column('phone_detail_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint("method IN ('proxy-v1','local-gop','azure','speechace')", name=op.f('ck_pron_scores_method')),
    sa.CheckConstraint("source IN ('speaking_turn','read_aloud','shadowing','minimal_pair')", name=op.f('ck_pron_scores_source')),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_pron_scores_score')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_pron_scores_profiles_profile_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['speaking_sessions.id'], name=op.f('fk_pron_scores_speaking_sessions_session_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['speaking_turns.id'], name=op.f('fk_pron_scores_speaking_turns_turn_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pron_scores'))
    )
    with op.batch_alter_table('pron_scores', schema=None) as batch_op:
        batch_op.create_index('ix_pron_scores_session', ['session_id', 'turn_id'], unique=False)
        batch_op.create_index('ix_pron_scores_word', ['profile_id', 'word', 'created_at'], unique=False)

    op.create_table('reading_answers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('qtype', sa.Text(), nullable=False),
    sa.Column('given', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('normalized', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('trap_analysis_json', sa.Text(), nullable=True),
    sa.CheckConstraint('correct IN (0,1)', name=op.f('ck_reading_answers_correct')),
    sa.ForeignKeyConstraint(['attempt_id'], ['reading_attempts.id'], name=op.f('fk_reading_answers_reading_attempts_attempt_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], name=op.f('fk_reading_answers_reading_questions_question_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_reading_answers_attempt_question')
    )
    with op.batch_alter_table('reading_answers', schema=None) as batch_op:
        batch_op.create_index('ix_reading_answers_q', ['question_id'], unique=False)
        batch_op.create_index('ix_reading_answers_type', ['qtype', 'correct'], unique=False)

    # ### end Alembic commands ###

    conn = op.get_bind()
    for name, target in DESC_INDEXES:
        op.execute(f"CREATE INDEX IF NOT EXISTS {name} ON {target}")
    create_vocab_fts(conn)
    create_views(conn)


def downgrade() -> None:
    conn = op.get_bind()
    drop_views(conn)
    drop_vocab_fts(conn)
    for name, _target in DESC_INDEXES:
        op.execute(f"DROP INDEX IF EXISTS {name}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_answers_type')
        batch_op.drop_index('ix_reading_answers_q')

    op.drop_table('reading_answers')
    with op.batch_alter_table('pron_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_pron_scores_word')
        batch_op.drop_index('ix_pron_scores_session')

    op.drop_table('pron_scores')
    with op.batch_alter_table('listening_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_listening_answers_type')
        batch_op.drop_index('ix_listening_answers_q')

    op.drop_table('listening_answers')
    op.drop_table('writing_evaluations')
    with op.batch_alter_table('srs_review_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_srs_review_logs_time')
        batch_op.drop_index('ix_srs_review_logs_card')

    op.drop_table('srs_review_logs')
    op.drop_table('speaking_turns')
    op.drop_table('reading_attempts')
    op.drop_table('listening_attempts')
    with op.batch_alter_table('writing_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_writing_submissions_prompt')
        batch_op.drop_index('ix_writing_submissions_parent')

    op.drop_table('writing_submissions')
    with op.batch_alter_table('vocab_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_vocab_sources_entry')

    op.drop_table('vocab_sources')
    with op.batch_alter_table('srs_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_srs_cards_due')

    op.drop_table('srs_cards')
    op.drop_table('speaking_sessions')
    with op.batch_alter_table('speaking_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_speaking_cards_set')
        batch_op.drop_index('ix_speaking_cards_pick')

    op.drop_table('speaking_cards')
    op.drop_table('reading_tests')
    with op.batch_alter_table('reading_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_questions_type')

    op.drop_table('reading_questions')
    with op.batch_alter_table('plan_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_sessions_day')

    op.drop_table('plan_sessions')
    op.drop_table('listening_tests')
    with op.batch_alter_table('listening_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_listening_questions_type')

    op.drop_table('listening_questions')
    with op.batch_alter_table('drill_results', schema=None) as batch_op:
        batch_op.drop_index('ix_drill_results_kind')

    op.drop_table('drill_results')
    with op.batch_alter_table('writing_prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_writing_prompts_pick')

    op.drop_table('writing_prompts')
    with op.batch_alter_table('vocab_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_vocab_entries_lemma')
        batch_op.drop_index('ix_vocab_entries_browse')

    op.drop_table('vocab_entries')
    op.drop_table('study_plans')
    with op.batch_alter_table('reading_passages', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_passages_pick')

    op.drop_table('reading_passages')
    op.drop_table('readiness_items')
    with op.batch_alter_table('pron_drill_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_pron_drills_contrast')

    op.drop_table('pron_drill_attempts')
    op.drop_table('practice_sessions')
    op.drop_table('placement_results')
    op.drop_table('milestones')
    with op.batch_alter_table('listening_scripts', schema=None) as batch_op:
        batch_op.drop_index('ix_listening_scripts_pick')

    op.drop_table('listening_scripts')
    op.drop_table('daily_activity')
    with op.batch_alter_table('card_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_card_sets_pick')

    op.drop_table('card_sets')
    with op.batch_alter_table('band_estimates', schema=None) as batch_op:
        batch_op.drop_index('ix_band_estimates_trend')

    op.drop_table('band_estimates')
    op.drop_table('adaptive_events')
    op.drop_table('activity_log')
    with op.batch_alter_table('vocab_pack_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_vocab_pack_entries_deck')

    op.drop_table('vocab_pack_entries')
    op.drop_table('topics')
    op.drop_table('settings')
    op.drop_table('profiles')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('ix_media_evict')

    op.drop_table('media_files')
    with op.batch_alter_table('llm_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_evals_calib')

    op.drop_table('llm_evaluations')
    op.drop_table('content_packs')
    # ### end Alembic commands ###
