"""The FastAPI application factory.

**Do not edit this file to register routes.** Every module inside
``bandready.server.routes`` is imported at startup and its module-level ``router`` is
included automatically. A route module that fails to import is logged and skipped — one
half-finished feature must never stop the app from booting, because Electron only shows
its window once ``/health`` answers.

Startup order (01 §4.1, 03 §2):
    init DB engine → run migrations → seed default settings → seed the content pack
    → start the job manager
Every step is individually guarded so a missing optional subsystem degrades to a warning.
"""

from __future__ import annotations

import importlib
import logging
import pkgutil
from contextlib import asynccontextmanager
from typing import Any

from fastapi import APIRouter, FastAPI
from fastapi.middleware.cors import CORSMiddleware

from bandready import __version__
from bandready.server.auth import DEV_ORIGINS, AccessLogMiddleware, AuthMiddleware
from bandready.server.errors import install_error_handlers
from bandready.server.jobs import job_manager

_log = logging.getLogger("bandready.app")


# --------------------------------------------------------------------------- startup

def _init_database() -> None:
    from bandready.db import engine as db_engine

    for name in ("init_engine", "init_db", "init"):
        fn = getattr(db_engine, name, None)
        if callable(fn):
            fn()
            _log.info("database engine initialised via %s()", name)
            return
    # No explicit initialiser: touching the engine is enough to create the file.
    getattr(db_engine, "get_engine", lambda: None)()
    _log.info("database engine ready")


def _run_migrations() -> None:
    from bandready.db import engine as db_engine

    for name in ("run_migrations", "upgrade_to_head", "migrate"):
        fn = getattr(db_engine, name, None)
        if callable(fn):
            fn()
            _log.info("migrations applied via bandready.db.engine.%s()", name)
            return

    from pathlib import Path

    from alembic import command
    from alembic.config import Config

    root = Path(__file__).resolve().parents[1]
    script_location = root / "migrations"
    if not script_location.exists():
        _log.warning("no alembic migrations directory at %s — skipping", script_location)
        return
    cfg = Config()
    cfg.set_main_option("script_location", str(script_location))
    url = getattr(db_engine, "database_url", None)
    if callable(url):
        cfg.set_main_option("sqlalchemy.url", url())
    command.upgrade(cfg, "head")
    _log.info("migrations applied via alembic at %s", script_location)


def _seed_settings() -> None:
    from bandready.settings_store import seed_defaults

    doc = seed_defaults()
    _log.info(
        "settings ready (llm=%s stt=%s tts=%s)",
        doc["llm"]["preset"], doc["stt"]["preset"], doc["tts"]["preset"],
    )


def _seed_content() -> None:
    try:
        from bandready.content.loader import seed_if_empty
    except ImportError:
        _log.info("content loader not available yet — skipping the default pack seed")
        return
    from bandready.db.engine import session_scope

    with session_scope() as session:
        result = seed_if_empty(session)
    _log.info("content pack seed: %s", result if result is not None else "already populated")


def _step(label: str, fn: Any, *, fatal: bool = False) -> None:
    try:
        fn()
    except ImportError as exc:
        _log.warning("startup step %r skipped — %s", label, exc)
    except Exception as exc:
        if fatal:
            raise
        _log.exception("startup step %r failed: %s", label, exc)


def run_startup() -> None:
    from bandready.config import get_settings
    from bandready.security.secrets import install_log_redaction

    settings = get_settings()
    settings.ensure_dirs()
    install_log_redaction()
    _log.info(
        "BandReady sidecar %s starting on %s (data dir %s, mock=%s)",
        __version__, settings.base_url, settings.data_dir, settings.enable_mock,
    )
    _step("database", _init_database)
    _step("migrations", _run_migrations)
    _step("settings", _seed_settings)
    _step("content", _seed_content)
    job_manager.start()


@asynccontextmanager
async def _lifespan(app: FastAPI):
    run_startup()
    try:
        yield
    finally:
        await job_manager.shutdown()
        _log.info("sidecar stopped")


# --------------------------------------------------------------------------- routers

def route_paths(app: FastAPI) -> list[str]:
    """Every registered path, flattened.

    FastAPI >= 0.140 includes routers lazily, so ``app.routes`` holds opaque
    ``_IncludedRouter`` wrappers rather than the individual routes. Introspection (tests,
    ``/api/v1/system/info``, the startup log) goes through here instead.
    """
    found: list[str] = []

    def walk(routes: Any) -> None:
        for route in routes or []:
            path = getattr(route, "path", None)
            if isinstance(path, str):
                found.append(path)
                continue
            inner = getattr(route, "original_router", None)
            if inner is not None:
                walk(getattr(inner, "routes", None))
            elif hasattr(route, "routes"):
                walk(route.routes)

    walk(app.routes)
    return sorted(set(found))


def discover_routers(app: FastAPI) -> list[str]:
    """Import every module in ``bandready.server.routes`` and include its ``router``."""
    from bandready.server import routes as routes_pkg

    registered: list[str] = []
    for module_info in sorted(
        pkgutil.iter_modules(routes_pkg.__path__), key=lambda m: m.name
    ):
        name = module_info.name
        if name.startswith("_"):
            continue
        full = f"{routes_pkg.__name__}.{name}"
        try:
            module = importlib.import_module(full)
        except Exception as exc:  # noqa: BLE001 — never fatal
            _log.error("route module %s failed to import and was skipped: %s", full, exc)
            continue
        router = getattr(module, "router", None)
        if not isinstance(router, APIRouter):
            _log.warning("route module %s has no module-level APIRouter named 'router'", full)
            continue
        app.include_router(router)
        paths = sorted({r.path for r in router.routes})  # type: ignore[attr-defined]
        registered.append(name)
        _log.info("registered routes from %s: %s", name, ", ".join(paths) or "(none)")
    return registered


# --------------------------------------------------------------------------- factory

def create_app() -> FastAPI:
    from bandready.config import get_settings

    settings = get_settings()

    app = FastAPI(
        title="BandReady sidecar",
        version=__version__,
        docs_url="/api/v1/docs",
        openapi_url="/api/v1/openapi.json",
        lifespan=_lifespan,
    )

    # CORS matters only in dev, where the SPA is served by Vite on another origin. In a
    # packaged app the renderer sends the bearer header itself and needs no allowance.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(DEV_ORIGINS),
        allow_origin_regex=r"^(app|file)://.*$",
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )
    app.add_middleware(AuthMiddleware, token=settings.auth_token)
    app.add_middleware(AccessLogMiddleware)

    install_error_handlers(app)
    app.state.registered_routes = discover_routers(app)
    app.state.route_paths = route_paths(app)
    return app


def __getattr__(name: str) -> Any:
    # `uvicorn bandready.server.app:app` works without building the app on every plain
    # `import bandready.server.app` (which the route auto-discovery itself performs).
    if name == "app":
        global app
        app = create_app()
        return app
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
